const CLUBS=['Dr','3W','5W','3H','4i','5i','6i','7i','8i','9i','PW','GW','SW','LW','Putt'];
const RESULTS=['Good','Left','Right','Short','Long','Penalty'];
const $=id=>document.getElementById(id);
const views=['homeView','setupView','roundView','summaryView','historyView'];
let round=null, selectedClub=null, selectedResult=null;
const store={getCurrent:()=>JSON.parse(localStorage.getItem('shottrack.current')||'null'),setCurrent:r=>localStorage.setItem('shottrack.current',JSON.stringify(r)),clearCurrent:()=>localStorage.removeItem('shottrack.current'),getHistory:()=>JSON.parse(localStorage.getItem('shottrack.history')||'[]'),saveHistory:r=>localStorage.setItem('shottrack.history',JSON.stringify([r,...store.getHistory()].slice(0,50)))};
function show(id,title){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));$('screenTitle').textContent=title;$('historyBtn').classList.toggle('hidden',id==='roundView');}
function init(){renderChips();const current=store.getCurrent();$('resumeBtn').classList.toggle('hidden',!current);renderLastRound();show('homeView','Golf, without the paperwork.');}
function renderChips(){$('clubGrid').innerHTML=CLUBS.map(c=>`<button class="chip" data-club="${c}">${c}</button>`).join('');$('resultGrid').innerHTML=RESULTS.map(r=>`<button class="chip" data-result="${r}">${r}</button>`).join('');document.querySelectorAll('[data-club]').forEach(b=>b.onclick=()=>{selectedClub=b.dataset.club;document.querySelectorAll('[data-club]').forEach(x=>x.classList.toggle('selected',x===b));});document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{selectedResult=selectedResult===b.dataset.result?null:b.dataset.result;document.querySelectorAll('[data-result]').forEach(x=>x.classList.toggle('selected',x.dataset.result===selectedResult));});}
function newRound(){show('setupView','Set up your round');$('courseInput').focus();}
function begin(){const holes=+$('holesInput').value,start=+$('startHoleInput').value||1;round={id:Date.now(),course:$('courseInput').value.trim()||'Unnamed Course',date:new Date().toISOString(),holesCount:holes,par:+$('parInput').value||72,currentHole:start,holes:{}};for(let i=1;i<=holes;i++)round.holes[i]={shots:[]};store.setCurrent(round);renderRound();show('roundView','On the course');}
function resume(){round=store.getCurrent();renderRound();show('roundView','On the course');}
function renderRound(){const h=round.currentHole,data=round.holes[h]||{shots:[]};$('courseName').textContent=round.course;$('holeNum').textContent=h;$('holeShots').textContent=data.shots.length;$('shotList').innerHTML=data.shots.length?data.shots.map((s,i)=>`<div class="shot"><span class="shot-num">${i+1}</span><div><strong>${s.club}</strong><small>${s.result||'Logged'}</small></div><small>${new Date(s.time).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></div>`).join(''):'<p class="empty">No shots yet.</p>';$('prevHoleBtn').disabled=h<=1;$('nextHoleBtn').textContent=h>=round.holesCount?'Review round →':'Next hole →';}
function resetPick(){selectedClub=null;selectedResult=null;document.querySelectorAll('.chip.selected').forEach(x=>x.classList.remove('selected'));}
function logShot(){if(!selectedClub){$('logHint').textContent='Pick a club first.';return;}const shots=round.holes[round.currentHole].shots;shots.push({club:selectedClub,result:selectedResult,time:new Date().toISOString()});store.setCurrent(round);$('logHint').textContent=`Shot ${shots.length} logged.`;resetPick();renderRound();if(navigator.vibrate)navigator.vibrate(30);}
function undo(){const shots=round.holes[round.currentHole].shots;if(shots.length){shots.pop();store.setCurrent(round);renderRound();}}
function moveHole(dir){const next=round.currentHole+dir;if(next>round.holesCount){finishPrompt();return;}if(next>=1){round.currentHole=next;store.setCurrent(round);resetPick();renderRound();window.scrollTo({top:0,behavior:'smooth'});}}
function totalShots(r){return Object.values(r.holes).reduce((n,h)=>n+h.shots.length,0)}
function finishPrompt(){if(!confirm('Finish this round? You can review it before starting another.'))return;round.completedAt=new Date().toISOString();store.saveHistory(round);store.clearCurrent();renderSummary(round);show('summaryView','Round summary');}
function renderSummary(r){const total=totalShots(r),diff=total-r.par,all=Object.values(r.holes).flatMap(h=>h.shots),penalties=all.filter(s=>s.result==='Penalty').length,good=all.filter(s=>s.result==='Good').length;$('summaryCourse').textContent=r.course;$('summaryScore').textContent=total;$('summaryVsPar').textContent=diff===0?'Even par':`${diff>0?'+':''}${diff} vs target ${r.par}`;$('summaryStats').innerHTML=`<div class="stat"><strong>${r.holesCount}</strong><span>Holes</span></div><div class="stat"><strong>${good}</strong><span>Good shots</span></div><div class="stat"><strong>${penalties}</strong><span>Penalties</span></div>`;$('holeSummary').innerHTML=Object.entries(r.holes).map(([n,h])=>`<div class="hole-row"><span>Hole ${n}</span><strong>${h.shots.length}</strong></div>`).join('');}
function renderLastRound(){const last=store.getHistory()[0],el=$('lastRound');if(!last){el.classList.add('hidden');return;}el.classList.remove('hidden');const score=totalShots(last);el.innerHTML=`<span class="eyebrow">LAST ROUND</span><strong class="history-score">${score}</strong><h3>${last.course}</h3><div class="history-meta">${new Date(last.date).toLocaleDateString()} · ${last.holesCount} holes</div>`;}
function history(){const items=store.getHistory();$('historyList').innerHTML=items.length?items.map(r=>`<div class="card history-item"><strong class="history-score">${totalShots(r)}</strong><span class="eyebrow">${new Date(r.date).toLocaleDateString()}</span><h3>${r.course}</h3><div class="history-meta">${r.holesCount} holes · target ${r.par}</div></div>`).join(''):'<div class="card empty">No completed rounds yet.</div>';show('historyView','Round history');}
function home(){round=null;renderLastRound();$('resumeBtn').classList.toggle('hidden',!store.getCurrent());show('homeView','Golf, without the paperwork.');}
$('newRoundBtn').onclick=newRound;$('resumeBtn').onclick=resume;$('beginBtn').onclick=begin;$('logShotBtn').onclick=logShot;$('undoBtn').onclick=undo;$('prevHoleBtn').onclick=()=>moveHole(-1);$('nextHoleBtn').onclick=()=>moveHole(1);$('finishBtn').onclick=finishPrompt;$('historyBtn').onclick=history;document.querySelectorAll('[data-home]').forEach(b=>b.onclick=home);init();