const CLUBS=['Dr','3W','5W','3H','4i','5i','6i','7i','8i','9i','PW','GW','SW','LW','Putt'];
const $=id=>document.getElementById(id),views=['homeView','setupView','roundView','summaryView','historyView'];
let round=null,selectedClub=null,selectedCourse=null,map=null,mapLayers=[],baseLayer=null;
const store={getCurrent:()=>{try{return JSON.parse(localStorage.getItem('shottrack.current')||'null')}catch{return null}},setCurrent:r=>localStorage.setItem('shottrack.current',JSON.stringify(r)),clearCurrent:()=>localStorage.removeItem('shottrack.current'),getHistory:()=>{try{return JSON.parse(localStorage.getItem('shottrack.history')||'[]')}catch{return[]}},saveHistory:r=>localStorage.setItem('shottrack.history',JSON.stringify([r,...store.getHistory()].slice(0,50)))};
function show(id,title){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));$('screenTitle').textContent=title;$('historyBtn').classList.toggle('hidden',id==='roundView');}
function normalizeRound(r){if(!r)return null;r.course=r.course||'Saved course';r.tee=r.tee||'Tee';r.holesCount=Number(r.holesCount)||18;r.currentHole=Math.min(r.holesCount,Math.max(1,Number(r.currentHole)||1));const lat=Number(r.courseCenter?.lat),lng=Number(r.courseCenter?.lng);r.courseCenter=Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:{lat:40.5363,lng:-111.8345};r.holes=r.holes||{};for(let i=1;i<=r.holesCount;i++){const h=r.holes[i]||{};r.holes[i]={...h,shots:Array.isArray(h.shots)?h.shots:[],start:h.start||null,par:h.par||null,yards:h.yards||null};}return r;}
function renderClubs(){$('clubGrid').innerHTML=CLUBS.map(c=>`<button class="chip" data-club="${c}">${c}</button>`).join('');document.querySelectorAll('[data-club]').forEach(b=>b.onclick=()=>{selectedClub=b.dataset.club;document.querySelectorAll('[data-club]').forEach(x=>x.classList.toggle('selected',x===b));const h=round?.holes?.[round.currentHole];$('mapPrompt').textContent=h&&!h.start?'Tap the starting ball position first.':`${selectedClub} selected — tap where the ball finished.`;});}
function init(){renderClubs();const current=normalizeRound(store.getCurrent());if(current)store.setCurrent(current);$('resumeBtn').classList.toggle('hidden',!current);renderLastRound();show('homeView','Your round, mapped.');}
async function searchCourses(){const q=$('courseSearch').value.trim();if(!q)return;$('courseResults').innerHTML='<p class="muted">Searching…</p>';try{const res=await fetch(`https://api.opengolfapi.org/v1/courses/search?q=${encodeURIComponent(q)}`);if(!res.ok)throw Error();const data=await res.json(),courses=(data.courses||[]).slice(0,8);$('courseResults').innerHTML=courses.length?courses.map((c,i)=>`<button class="course-option" data-course="${i}"><strong>${c.course_name}</strong><small>${c.city||''}${c.state?', '+c.state:''} · ${c.holes||18} holes · Par ${c.par||'—'}</small></button>`).join(''):'<p class="muted">No courses found.</p>';document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>selectCourse(courses[+b.dataset.course]));}catch{$('courseResults').innerHTML='<p class="muted">Course search could not load. Try again.</p>';}}
async function selectCourse(c){selectedCourse=c;$('courseResults').innerHTML='';$('selectedCourse').classList.remove('hidden');$('selectedCourse').innerHTML=`<strong>${c.course_name}</strong><br>${c.city||''}, ${c.state||''} · Par ${c.par||'—'}`;$('beginBtn').disabled=false;try{const res=await fetch(`https://api.opengolfapi.org/v1/courses/${c.id}`);if(res.ok){const detail=await res.json();selectedCourse={...c,...detail};populateTees(detail);}}catch{}}
function populateTees(d){const names=new Set();const scan=o=>{if(!o||typeof o!=='object')return;Object.keys(o).forEach(k=>{if(/^(black|blue|white|gold|silver|red|green|web)$/i.test(k))names.add(k);const v=o[k];if(v&&typeof v==='object')scan(v);});};scan(d);if(names.size)$('teeInput').innerHTML=[...names].map(n=>`<option>${n[0].toUpperCase()+n.slice(1)}</option>`).join('');}
function begin(){if(!selectedCourse)return;const start=+$('startHoleInput').value||1;round={id:Date.now(),course:selectedCourse.course_name,courseId:selectedCourse.id,date:new Date().toISOString(),par:+selectedCourse.par||72,holesCount:+selectedCourse.holes||18,tee:$('teeInput').value,currentHole:start,courseCenter:{lat:Number(selectedCourse.lat),lng:Number(selectedCourse.lng)},holes:{}};for(let i=1;i<=round.holesCount;i++)round.holes[i]={shots:[],start:null,par:null,yards:null};hydrateHoles(selectedCourse);round=normalizeRound(round);store.setCurrent(round);show('roundView','Tap. Track. Play.');setTimeout(()=>{ensureMap();renderRound();},150);}
function hydrateHoles(d){const candidates=d.holes||d.scorecard?.holes||d.course?.holes||[];if(Array.isArray(candidates))candidates.forEach(h=>{const n=+(h.number||h.hole||h.hole_number);if(!round.holes[n])return;round.holes[n].par=+h.par||null;const y=h.yardages||{};round.holes[n].yards=+(y[round.tee?.toLowerCase()]||y.web||h.yards||0)||null;});}
function resume(){round=normalizeRound(store.getCurrent());if(!round)return home();store.setCurrent(round);show('roundView','Tap. Track. Play.');setTimeout(()=>{ensureMap();renderRound();},150);}
function ensureMap(){if(!window.L){$('mapPrompt').textContent='Map engine did not load — refresh the page.';return;}if(map){map.invalidateSize(true);return;}const c=round?.courseCenter||{lat:40.5363,lng:-111.8345};map=L.map('map',{zoomControl:true,preferCanvas:true}).setView([c.lat,c.lng],17);baseLayer=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{minZoom:2,maxZoom:19,detectRetina:true,crossOrigin:true,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);let errors=0;baseLayer.on('tileerror',()=>{errors++;if(errors===3){$('mapPrompt').textContent='Map tiles did not load. Shot tracking is still active.';$('mapReadout').textContent='OpenStreetMap basemap returned tile errors.';}});baseLayer.on('load',()=>{$('mapReadout').textContent='Map ready — tap your starting ball position.';});map.on('click',e=>mapTap(e.latlng));requestAnimationFrame(()=>map.invalidateSize(true));setTimeout(()=>map.invalidateSize(true),400);}
function mapTap(p){if(!round)return;const h=round.holes[round.currentHole];if(!h.start){h.start={lat:p.lat,lng:p.lng};store.setCurrent(round);$('mapPrompt').textContent=selectedClub?`${selectedClub} selected — now tap where it landed.`:'Start placed — choose a club, then tap where it landed.';renderMap();return;}if(!selectedClub){$('mapPrompt').textContent='Choose a club, then tap where the ball finished.';return;}const prev=h.shots.length?h.shots[h.shots.length-1].end:h.start,end={lat:p.lat,lng:p.lng},yards=Math.round(distanceMeters(prev,end)*1.0936133);h.shots.push({club:selectedClub,start:{...prev},end,yards,time:new Date().toISOString()});selectedClub=null;document.querySelectorAll('.chip.selected').forEach(x=>x.classList.remove('selected'));store.setCurrent(round);$('mapPrompt').textContent=`${yards} yd logged — choose the next club.`;renderRound();if(navigator.vibrate)navigator.vibrate(25);}
function distanceMeters(a,b){const R=6371008.8,toRad=x=>x*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lng-a.lng),la1=toRad(a.lat),la2=toRad(b.lat);const x=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x));}
function renderRound(){round=normalizeRound(round);const n=round.currentHole,d=round.holes[n];$('courseName').textContent=`${round.course} · ${round.tee}`;$('holeNum').textContent=n;$('holeMeta').textContent=[d.par&&`Par ${d.par}`,d.yards&&`${d.yards} yd`].filter(Boolean).join(' · ');$('holeShots').textContent=d.shots.length;$('shotList').innerHTML=d.shots.length?d.shots.map((s,i)=>`<div class="shot"><span class="shot-num">${i+1}</span><div><strong>${s.club}</strong><small>${s.yards} yards</small></div><small>${Number(s.end.lat).toFixed(5)}, ${Number(s.end.lng).toFixed(5)}</small></div>`).join(''):'<p class="empty">Place the start point, choose a club, then tap each landing spot.</p>';$('totalHoleDistance').textContent=d.shots.length?`${d.shots.reduce((n,s)=>n+(s.yards||0),0)} yd tracked`:'';$('prevHoleBtn').disabled=n<=1;$('nextHoleBtn').textContent=n>=round.holesCount?'Review round →':'Next hole →';renderMap();}
function renderMap(){if(!map||!round)return;mapLayers.forEach(l=>{try{map.removeLayer(l)}catch{}});mapLayers=[];const d=round.holes[round.currentHole],pts=[];if(d.start){pts.push(d.start);addMarker(d.start,'S',true);}d.shots.forEach((s,i)=>{if(!s.end||!s.start)return;pts.push(s.end);addMarker(s.end,String(i+1));const line=L.polyline([[s.start.lat,s.start.lng],[s.end.lat,s.end.lng]],{color:'#d9f99d',weight:4,opacity:.95}).addTo(map);mapLayers.push(line);});if(pts.length>1)map.fitBounds(pts.map(p=>[p.lat,p.lng]),{padding:[45,45],maxZoom:18});else if(pts.length===1)map.setView([pts[0].lat,pts[0].lng],18);else map.setView([round.courseCenter.lat,round.courseCenter.lng],17);$('mapReadout').textContent=d.start?'Start is set. Every landing tap stores exact coordinates.':'First tap sets the starting ball position.';setTimeout(()=>map.invalidateSize(true),0);}
function addMarker(p,label,start=false){const icon=L.divIcon({className:'',html:`<div class="shot-marker ${start?'start-marker':''}">${label}</div>`,iconSize:[24,24],iconAnchor:[12,12]});mapLayers.push(L.marker([p.lat,p.lng],{icon}).addTo(map));}
function undo(){const d=round.holes[round.currentHole];if(d.shots.length)d.shots.pop();else d.start=null;store.setCurrent(round);renderRound();}
function clearStart(){const d=round.holes[round.currentHole];if(d.shots.length&&!confirm('Reset this entire hole?'))return;d.start=null;d.shots=[];selectedClub=null;document.querySelectorAll('.chip.selected').forEach(x=>x.classList.remove('selected'));store.setCurrent(round);renderRound();$('mapPrompt').textContent='Tap your starting ball position first.';}
function moveHole(dir){const n=round.currentHole+dir;if(n>round.holesCount){finish();return;}if(n>=1){round.currentHole=n;selectedClub=null;store.setCurrent(round);renderRound();$('mapPrompt').textContent=round.holes[n].start?'Choose a club, then tap where it lands.':'Tap your starting ball position first.';window.scrollTo({top:0,behavior:'smooth'});}}
function totalShots(r){return Object.values(r.holes||{}).reduce((n,h)=>n+(h.shots?.length||0),0)}
function finish(){if(!confirm('Finish this round?'))return;round.completedAt=new Date().toISOString();store.saveHistory(round);store.clearCurrent();renderSummary(round);show('summaryView','Round summary');}
function renderSummary(r){const total=totalShots(r),diff=total-r.par,tracked=Object.values(r.holes).flatMap(h=>h.shots||[]).reduce((n,s)=>n+(s.yards||0),0);$('summaryCourse').textContent=r.course;$('summaryScore').textContent=total;$('summaryVsPar').textContent=`${diff>=0?'+':''}${diff} vs par ${r.par}`;$('summaryStats').innerHTML=`<div class="stat"><strong>${r.holesCount}</strong><span>Holes</span></div><div class="stat"><strong>${total}</strong><span>Shots</span></div><div class="stat"><strong>${tracked}</strong><span>Yards mapped</span></div>`;$('holeSummary').innerHTML=Object.entries(r.holes).map(([n,h])=>`<div class="hole-row"><span>Hole ${n}</span><strong>${h.shots.length}</strong></div>`).join('');}
function renderLastRound(){const last=store.getHistory()[0],el=$('lastRound');if(!last){el.classList.add('hidden');return;}el.classList.remove('hidden');el.innerHTML=`<span class="eyebrow">LAST ROUND</span><strong class="history-score">${totalShots(last)}</strong><h3>${last.course||'Saved course'}</h3><div class="history-meta">${new Date(last.date).toLocaleDateString()} · ${last.holesCount||18} holes</div>`;}
function history(){const items=store.getHistory();$('historyList').innerHTML=items.length?items.map(r=>`<div class="card"><strong class="history-score">${totalShots(r)}</strong><span class="eyebrow">${new Date(r.date).toLocaleDateString()}</span><h3>${r.course||'Saved course'}</h3><div class="history-meta">${r.holesCount||18} holes · ${r.tee||'Tee'} tees</div></div>`).join(''):'<div class="card empty">No completed rounds yet.</div>';show('historyView','Round history');}
function home(){round=null;selectedCourse=null;renderLastRound();$('resumeBtn').classList.toggle('hidden',!store.getCurrent());show('homeView','Your round, mapped.');}
$('newRoundBtn').onclick=()=>show('setupView','Choose your course');$('searchCourseBtn').onclick=searchCourses;$('courseSearch').addEventListener('keydown',e=>{if(e.key==='Enter')searchCourses();});$('beginBtn').onclick=begin;$('resumeBtn').onclick=resume;$('undoBtn').onclick=undo;$('clearStartBtn').onclick=clearStart;$('prevHoleBtn').onclick=()=>moveHole(-1);$('nextHoleBtn').onclick=()=>moveHole(1);$('finishBtn').onclick=finish;$('historyBtn').onclick=history;document.querySelectorAll('[data-home]').forEach(b=>b.onclick=home);init();