// ShotTrack V3 course picker — resilient location-first course discovery.
(()=>{const $=id=>document.getElementById(id),KEY='shottrack.recentCourses';let userPos=null,timer=null,latest=[],seq=0,nearCache=[];
const css=document.createElement('style');css.textContent=`.course-picker-head{display:flex;justify-content:space-between;align-items:center;margin:10px 0 6px}.course-picker-head strong{font-size:14px}.course-picker-head button{border:0;background:none;text-decoration:underline;color:#466158;cursor:pointer}.course-list.all{max-height:430px;overflow-y:auto;padding-right:5px}.course-card{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:11px 0;border-bottom:1px solid #e7ece8}.course-main{border:0;background:none;text-align:left;padding:0;cursor:pointer}.course-main strong,.course-main small{display:block}.course-main small{color:#718078;margin-top:3px}.course-remove{border:0;background:#f1f4f2;border-radius:8px;padding:7px 9px;cursor:pointer}.course-picker-msg{color:#718078;font-size:13px;padding:9px 0}.distance-badge{font-weight:700;color:#355b4d}.location-line{font-size:12px;color:#718078;margin:5px 0 10px}`;document.head.appendChild(css);
const rec=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}},save=c=>{const k=String(c.place_id||c.id||c.course_name);localStorage.setItem(KEY,JSON.stringify([c,...rec().filter(x=>String(x.place_id||x.id||x.course_name)!==k)].slice(0,8)))},remove=k=>{localStorage.setItem(KEY,JSON.stringify(rec().filter(x=>String(x.place_id||x.id||x.course_name)!==String(k))));showRecent()},esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m])),rad=x=>x*Math.PI/180,miles=(a,b)=>{if(!a||!b)return null;const d1=rad(b.lat-a.lat),d2=rad(b.lng-a.lng),x=Math.sin(d1/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(d2/2)**2;return 7917.5226*Math.asin(Math.sqrt(x))},pos=c=>{const lat=Number(c.lat),lng=Number(c.lng);return Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null},distance=c=>miles(userPos,pos(c)),dist=c=>{const d=distance(c);return d==null?'distance unavailable':`${d<10?d.toFixed(1):Math.round(d)} mi away`};
function render(cs,{recent=false,title='Courses',all=false}={}){latest=cs;const box=$('courseResults');box.innerHTML=`<div class="course-picker-head"><strong>${esc(title)}</strong>${recent?'':'<button id="allCourses">View all courses</button>'}</div>${userPos?'<div class="location-line">Using your current location · nearest first</div>':'<div class="location-line">Location unavailable — allow location for mileage</div>'}<div class="course-list ${all?'all':''}">`+(cs.length?cs.map((c,i)=>`<div class="course-card"><button class="course-main" data-pick="${i}"><strong>${esc(c.course_name)}</strong><small>${esc(c.address||[c.city,c.state].filter(Boolean).join(', '))}${userPos&&pos(c)?` · <span class="distance-badge">${esc(dist(c))}</span>`:''}</small></button>${recent?`<button class="course-remove" data-remove="${esc(c.place_id||c.id||c.course_name)}">Remove</button>`:''}</div>`).join(''):'<div class="course-picker-msg">No courses found.</div>')+'</div>';box.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>choose(latest[+b.dataset.pick]));box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=e=>{e.stopPropagation();remove(b.dataset.remove)});$('allCourses')?.addEventListener('click',()=>search($('courseSearch').value.trim(),true))}
function showRecent(){const r=rec();r.length?render(r,{recent:true,title:'Recently viewed'}):search('',false)}
function coord(v){if(v==null)return NaN;return Number(typeof v==='function'?v():v)}function normalizeGoogle(p){const l=p.location;return{place_id:p.id||p.placeId||'',course_name:(typeof p.displayName==='string'?p.displayName:p.displayName?.text)||p.name||'Golf course',address:p.formattedAddress||'',lat:coord(l?.lat),lng:coord(l?.lng),_google:true}}
async function googleNearby(){if(!window.google?.maps?.places?.PlacesService)return[];return new Promise(resolve=>{const el=document.createElement('div'),svc=new google.maps.places.PlacesService(el);svc.nearbySearch({location:new google.maps.LatLng(userPos.lat,userPos.lng),radius:50000,type:'golf_course'},(results,status)=>{if(status!==google.maps.places.PlacesServiceStatus.OK&&status!==google.maps.places.PlacesServiceStatus.ZERO_RESULTS)return resolve([]);resolve((results||[]).map(p=>{const l=p.geometry?.location;return{place_id:p.place_id||'',course_name:p.name||'Golf course',address:p.vicinity||'',lat:coord(l?.lat),lng:coord(l?.lng),_google:true}}).filter(c=>pos(c)))})})}
async function osmNearby(radius=100000){const q=`[out:json][timeout:15];nwr["leisure"="golf_course"](around:${radius},${userPos.lat},${userPos.lng});out center tags;`;for(const host of ['https://overpass.kumi.systems/api/interpreter','https://overpass-api.de/api/interpreter'])try{const r=await fetch(`${host}?data=${encodeURIComponent(q)}`);if(!r.ok)continue;const d=await r.json();return(d.elements||[]).map(e=>{const t=e.tags||{};return{course_name:t.name||'',address:[t['addr:street'],t['addr:city'],t['addr:state']].filter(Boolean).join(', '),lat:Number(e.lat??e.center?.lat),lng:Number(e.lon??e.center?.lon),_osm:true}}).filter(c=>c.course_name&&pos(c))}catch{}return[]}
function dedupe(cs){const seen=new Set;return cs.filter(c=>{const k=c.course_name.toLowerCase().replace(/[^a-z0-9]/g,'');if(seen.has(k))return false;seen.add(k);return true})}
async function getNearby(force=false){if(nearCache.length&&!force)return nearCache;let cs=[];try{cs=await googleNearby()}catch{}if(cs.length<8){try{cs=dedupe([...cs,...await osmNearby(120000)])}catch{}}nearCache=cs.filter(c=>pos(c)).sort((a,b)=>distance(a)-distance(b));return nearCache}
async function nearby(all=false){const my=++seq;if(!userPos){$('courseResults').innerHTML='<div class="course-picker-msg">Waiting for location permission. Allow location access to show nearby courses and distances.</div>';return}const box=$('courseResults');box.innerHTML='<div class="course-picker-msg">Finding golf courses near you…</div>';const cs=await getNearby(all);if(my!==seq)return;render(all?cs:cs.slice(0,8),{title:all?'Golf courses by distance':'Courses near you',all})}
function scoreName(name,q){name=name.toLowerCase();q=q.toLowerCase();if(name===q)return 0;if(name.startsWith(q))return 1;if(name.includes(q))return 2;const words=q.split(/\s+/).filter(Boolean);return 3+words.filter(w=>name.includes(w)).length*-0.1}
async function localSearch(q,all=false){const my=++seq,box=$('courseResults');box.innerHTML='<div class="course-picker-msg">Searching nearby golf courses…</div>';let cs=await getNearby(false);if(my!==seq)return;cs=cs.map(c=>({c,s:scoreName(c.course_name,q)})).filter(x=>x.s<3).sort((a,b)=>a.s-b.s||distance(a.c)-distance(b.c)).map(x=>x.c);if(!cs.length){try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=15&countrycodes=us&q=${encodeURIComponent(q+' golf course')}`),d=await r.json();cs=d.map(x=>({course_name:(x.name||x.display_name.split(',')[0]),address:x.display_name,lat:Number(x.lat),lng:Number(x.lon),_osm:true})).filter(c=>pos(c)).sort((a,b)=>scoreName(a.course_name,q)-scoreName(b.course_name,q)||distance(a)-distance(b))}catch{}}if(my!==seq)return;render(all?cs:cs.slice(0,8),{title:all?'All matching courses':'Best nearby matches',all})}
async function search(q,all){return q?localSearch(q,all):nearby(all)}
async function choose(c){save(c);try{const r=await fetch(`https://api.opengolfapi.org/v1/courses/search?q=${encodeURIComponent(c.course_name)}`);if(r.ok){const d=await r.json(),m=(d.courses||[])[0];if(m)c={...m,course_name:c.course_name,lat:c.lat,lng:c.lng,address:c.address,place_id:c.place_id,_locationSource:true}}}catch{}selectCourse(c)}
function locate(){if(!navigator.geolocation){$('courseResults').innerHTML='<div class="course-picker-msg">This browser cannot provide location.</div>';return}navigator.geolocation.getCurrentPosition(p=>{userPos={lat:Number(p.coords.latitude),lng:Number(p.coords.longitude)};nearCache=[];if(document.activeElement===$('courseSearch')&&!$('courseSearch').value.trim())showRecent()},()=>{$('courseResults').innerHTML='<div class="course-picker-msg">Location permission is off. Allow Location for nearby courses and mileage.</div>'},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
function init(){const input=$('courseSearch'),button=$('searchCourseBtn');if(!input)return;input.addEventListener('focus',()=>{if(!input.value.trim())showRecent()});input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>search(input.value.trim(),false),350)});input.addEventListener('keydown',e=>{if(e.key==='Enter'){clearTimeout(timer);search(input.value.trim(),false)}});if(button){button.textContent='View all courses';button.onclick=()=>search(input.value.trim(),true)}locate()}document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init()})();