// ShotTrack V3 course picker: recents + true geographic nearby discovery + name search.
(() => {
 const $=id=>document.getElementById(id),KEY='shottrack.recentCourses';let userPos=null,timer=null,latest=[];
 const css=document.createElement('style');css.textContent=`.course-picker-head{display:flex;justify-content:space-between;align-items:center;margin:10px 0 6px}.course-picker-head strong{font-size:14px}.course-picker-head button{border:0;background:none;text-decoration:underline;color:#466158;cursor:pointer}.course-card{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:11px 0;border-bottom:1px solid #e7ece8}.course-main{border:0;background:none;text-align:left;padding:0;cursor:pointer}.course-main strong,.course-main small{display:block}.course-main small{color:#718078;margin-top:3px}.course-remove{border:0;background:#f1f4f2;border-radius:8px;padding:7px 9px}.course-picker-msg{color:#718078;font-size:13px;padding:8px 0}`;document.head.appendChild(css);
 const rec=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}},save=c=>{const k=String(c.id||c.course_name);localStorage.setItem(KEY,JSON.stringify([c,...rec().filter(x=>String(x.id||x.course_name)!==k)].slice(0,8)))},remove=k=>{localStorage.setItem(KEY,JSON.stringify(rec().filter(x=>String(x.id||x.course_name)!==String(k))));showRecent()};
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),rad=x=>x*Math.PI/180,miles=(a,b)=>{if(!a||!b)return null;const d1=rad(b.lat-a.lat),d2=rad(b.lng-a.lng),x=Math.sin(d1/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(d2/2)**2;return 7917.5226*Math.asin(Math.sqrt(x))},pos=c=>{const lat=Number(c.lat??c.latitude??c.location?.lat),lng=Number(c.lng??c.lon??c.longitude??c.location?.lng);return Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null};
 const dist=c=>{const d=miles(userPos,pos(c));return d==null?'':`${d<10?d.toFixed(1):Math.round(d)} mi away`};
 function render(cs,{recent=false,title='Courses'}={}){latest=cs;const box=$('courseResults');box.innerHTML=`<div class="course-picker-head"><strong>${esc(title)}</strong>${recent?'':'<button id="allCourses">View all courses</button>'}</div>`+(cs.length?cs.map((c,i)=>`<div class="course-card"><button class="course-main" data-pick="${i}"><strong>${esc(c.course_name||c.name)}</strong><small>${esc([c.city,c.state].filter(Boolean).join(', '))}${dist(c)?` · ${dist(c)}`:''}</small></button>${recent?`<button class="course-remove" data-remove="${esc(c.id||c.course_name)}">Remove</button>`:''}</div>`).join(''):'<div class="course-picker-msg">No matching courses found.</div>');box.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{const c=latest[+b.dataset.pick];save(c);selectCourse(c)});box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=e=>{e.stopPropagation();remove(b.dataset.remove)});$('allCourses')?.addEventListener('click',()=>nameSearch($('courseSearch').value.trim(),true));}
 function showRecent(){const r=rec();if(r.length)render(r,{recent:true,title:'Recently viewed'});else nearby();}
 async function nearby(){const box=$('courseResults');if(!userPos){box.innerHTML='<div class="course-picker-msg">Getting your location to find nearby courses…</div>';return;}box.innerHTML='<div class="course-picker-msg">Finding courses near you…</div>';try{const q=`[out:json][timeout:12];nwr["leisure"="golf_course"](around:80000,${userPos.lat},${userPos.lng});out center tags;`,r=await fetch(`https://overpass-api.de/api/interpreter?data=${encodeURIComponent(q)}`);if(!r.ok)throw Error();const d=await r.json();let cs=(d.elements||[]).map(e=>{const p={lat:Number(e.lat??e.center?.lat),lng:Number(e.lon??e.center?.lon)},t=e.tags||{};return{course_name:t.name||'Unnamed golf course',city:t['addr:city']||'',state:t['addr:state']||'',lat:p.lat,lng:p.lng,_osm:true}}).filter(c=>Number.isFinite(c.lat)&&Number.isFinite(c.lng)&&c.course_name!=='Unnamed golf course').sort((a,b)=>miles(userPos,pos(a))-miles(userPos,pos(b))).slice(0,8);render(cs,{title:'Courses near you'});}catch{box.innerHTML='<div class="course-picker-msg">Could not load nearby courses. Type a course name to search.</div>';}}
 async function nameSearch(q,all=false){if(!q){if(all){render([],{title:'Type a course name to view courses anywhere'});return;}return nearby();}const box=$('courseResults');box.innerHTML='<div class="course-picker-msg">Searching courses…</div>';try{const r=await fetch(`https://api.opengolfapi.org/v1/courses/search?q=${encodeURIComponent(q)}`);if(!r.ok)throw Error();const d=await r.json(),qa=q.toLowerCase();let cs=(d.courses||[]).map((c,i)=>({c,i,d:miles(userPos,pos(c)),n:String(c.course_name||'').toLowerCase()})).sort((a,b)=>{const rank=x=>x.n===qa?0:x.n.startsWith(qa)?1:x.n.includes(qa)?2:3,dr=rank(a)-rank(b);if(dr)return dr;if(a.d!=null&&b.d!=null)return a.d-b.d;if(a.d!=null)return-1;if(b.d!=null)return 1;return a.i-b.i}).map(x=>x.c);if(!all)cs=cs.slice(0,8);render(cs,{title:all?'All matching courses':'Best matches'});}catch{box.innerHTML='<div class="course-picker-msg">Course search could not load.</div>';}}
 function locate(){if(!navigator.geolocation){$('courseResults').innerHTML='<div class="course-picker-msg">Type a course name to search.</div>';return;}navigator.geolocation.getCurrentPosition(p=>{userPos={lat:p.coords.latitude,lng:p.coords.longitude};if(document.activeElement===$('courseSearch')&&!$('courseSearch').value.trim()&&!rec().length)nearby();},()=>{$('courseResults').innerHTML='<div class="course-picker-msg">Location is off. Type a course name, or enable location for nearby courses.</div>';},{enableHighAccuracy:true,timeout:8000,maximumAge:120000});}
 function init(){const input=$('courseSearch'),button=$('searchCourseBtn');if(!input)return;input.addEventListener('focus',()=>{if(!input.value.trim())showRecent()});input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>input.value.trim()?nameSearch(input.value.trim(),false):showRecent(),220)});if(button){button.textContent='View all courses';button.onclick=()=>nameSearch(input.value.trim(),true)}locate();}
 const old=window.selectCourse;window.selectCourse=async c=>{save(c);return old(c)};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();